site:
  title: Kien's Knowledge Base
  url: http://localhost:3000
  start_page: knowledge_base::00_index.adoc
content:
  sources:
    - url: ./
      start_path: docs
      branches: [HEAD]
ui:
  bundle:
    url: ./ui/dist
    snapshot: true
output:
  dir: dist/
asciidoc:
  sourcemap: true
