site:
  title: Kien's Knowledge Base
  url: /
  start_page: knowledge_base::00_index.adoc
  robots: disallow
content:
  sources:
    - url: ./
      start_path: docs
      branches: [HEAD]
ui:
  bundle:
    url: ./ui/dist
    snapshot: true
  supplemental_files:
    # Copy the .nojekyll file to the root of the output directory
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
output:
  dir: dist/
asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-kroki
antora:
  extensions:
    - require: '@antora/lunr-extension'
