= AWS Nitro System

AWS Nitro System is the underlying platform for **new xref:aws_elastic_compute_cloud.adoc[] instances** that allows better performance and reduce cost.

AWS Nitro System contains the following components:

* *Nitro Hypervisor*: Lightweight hypervisor that manages memory, CPU. It offloads most of the functionality to dedicated hardware that performs access to various AWS services, such as Networking, Storage, etc.
* *Nitro Security Chip*: Provide security to instances by preventing EC2 or bare-metal instances from making changes to firmware devices. Nitro Security Chip implements Nitro Root of Trust, which blocks access to physical stores.
* Nitro cards: A set of dedicated hardware that perform tasks that previously done in software by Hypervisors
* Nitro Card for xref:aws_virtual_private_cloud.adoc[VPC]: Functions as a NIC and provides Networking connectivity. This acts as VPC data plane that provides routing, firewall (via security groups), etc.
* Nitro Card for AWS Elastic Block Store|EBS: Allow connection to AWS Elastic Block Store, provides encryption support and NVM to remote storage protocol
* Nitro Card for Instance Store: Allow connections to SDD/HDD directly attached to AWS physical servers
* Nitro Card controller: Coordinate Nitro Cards, Nitro Hypervisor and Nitro Security Chip

This Nitro System allows AWS to innovate faster and allow it to provide new features such as 100 Gbps networking or xref:aws_elastic_fabric_adapter.adoc[] to instances, as well as allow support for different architecture (ARM or AMD) faster

== Related

* AWS Nitro Enclaves

== Resources
* https://www.youtube.com/watch?v=rUY-00yFlE4[AWS re:Invent 2019: Powering next-gen Amazon EC2: Deep dive into the Nitro System]
